services:
  eureka-service:
    container_name: eureka-service
    build:
      context: eureka
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - spring-cloud
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      start_interval: 10s
      timeout: 10s
      retries: 10

  gateway-service:
    container_name: gateway-service
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - spring-cloud
    depends_on:
      eureka-service:
        condition: service_healthy

  customer-service-1:
    container_name: customer-service-1
    build:
      context: customer-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      eureka-service:
        condition: service_healthy


  customer-service-2:
    container_name: customer-service-2
    build:
      context: customer-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      eureka-service:
        condition: service_healthy


  warehouse-service-1:
    container_name: warehouse-service-1
    build:
      context: warehouse-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      eureka-service:
        condition: service_healthy


  warehouse-service-2:
    container_name: warehouse-service-2
    build:
      context: warehouse-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      eureka-service:
        condition: service_healthy


networks:
  spring-cloud:
    driver: bridge
