services:
  eureka-service:
    build:
      context: eureka
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  gateway-service:
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  customer-service-1:
    build:
      context: customer-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  customer-service-2:
    build:
      context: customer-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  warehouse-service-1:
    build:
      context: warehouse-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  warehouse-service-2:
    build:
      context: warehouse-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

networks:
  spring-cloud:
    driver: bridge
