services:
  eureka-service:
    image: eureka-service
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  gateway-service:
    image: gateway-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  customer-service-1:
    image: customer-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8100:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  customer-service-2:
    image: customer-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8101:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  warehouse-service-1:
    image: warehouse-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8102:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

  warehouse-service-2:
    image: warehouse-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka
    ports:
      - "8103:8080"
    networks:
      - spring-cloud
    depends_on:
      - eureka-service

networks:
  spring-cloud:
    driver: bridge
