server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - UniqueIdGenerator
            - OpenApiValidation

        - id: warehouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/api/v1/warehouse/**
          filters:
            - UniqueIdGenerator

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
