server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: dummy-service
          uri: lb://dummy-service
          predicates:
            - Path=/dummy/**
          filters:
            - UniqueIdGenerator
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
