openapi: "3.1.0"
info:
  title: "service_2 API"
  description: "service_2 API"
  version: "1.0.0"
servers:
  - url: "https://service_2"
paths:
  /api/v1/warehouse/stocks:
    get:
      summary: "GET api/v1/stocks"
      operationId: "getAllStocks"
      parameters:
        - name: "X-Unique-Id"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StockReservationProjection"
    post:
      summary: "POST api/v1/stocks"
      operationId: "createOrUpdateStock"
      parameters:
        - name: "X-Unique-Id"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReserveProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /api/v1/warehouse/stocks/{clientId}:
    get:
      summary: "GET api/v1/stocks/{clientId}"
      operationId: "getStock"
      parameters:
        - name: "clientId"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "X-Unique-Id"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StockReservationProjection"
components:
  schemas:
    StockReservationProjection:
      type: "object"
      properties:
        productId:
          type: "string"
        quantity:
          type: "integer"
          format: "int32"
    ReserveProductRequest:
      type: "object"
      properties:
        id:
          type: "string"
        quantity:
          type: "integer"
          format: "int32"
    Void:
      type: "object"
      properties: { }